WizardForm/Models/ErrorViewModel.cs
namespace WizardForm.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WizardForm/Models/Info.cs
namespace WizardForm.Models
{
    public class Info
    {
        public int Id { get; set; }
        public string Information { get; set; }
    }
}

WizardForm/Models/S1.cs
namespace WizardForm.Models
{
    public class S1 : StepViewModel
    {
        public string FirstName { get; set; }

        public S1()
        {
            Position = 0;
        }
    }
}

WizardForm/Models/S2.cs
namespace WizardForm.Models
{
    public class S2 : StepViewModel
    {
        public string LastName { get; set; }

        public S2()
        {
            Position = 1;
        }
    }
}

WizardForm/Models/StepViewModel.cs
namespace WizardForm.Models
{
    public class StepViewModel
    {
        public int Position { get; set; }
    }
}

WizardForm/Controllers/WizardController.cs
using Infrastructure.Data;
using Infrastructure.Dto;
using Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WizardForm.Models;

namespace WizardForm.Controllers
{
    public class WizardController : Controller
    {
        private readonly ILogger<WizardController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly EmailConfigSettings _emailConfigurationSettings;
        private readonly IEmailSender _emailSender;
        private readonly IWizardService _wizardService;

        public WizardController(
            ILogger<WizardController> logger,
            ApplicationDbContext context,
            EmailConfigSettings emailConfigSettings,
            IEmailSender emailSender,
            IWizardService wizardService)
        {
            _logger = logger;
            _context = context;
            _emailSender = emailSender;
            _emailConfigurationSettings = emailConfigSettings;
            _wizardService = wizardService;
        }

        public async Task<IActionResult> Index()
        {
            Dictionary<string, StepViewModel> wiz = new Dictionary<string, StepViewModel>();
            wiz.Add("S1", new StepViewModel());
            wiz.Add("S2", new StepViewModel());


            return View(wiz);
        }

        public async Task<IActionResult> Messages()
        {
            // var viewModel = await _context.Messages
            //     .Include(i => i.Topic)
            //     .ToListAsync();

            var m = _wizardService.GetAllAsync();
            return View(m);
        }

        public IActionResult StepOne()
        {
            var topics = from bc in _context.Topics
                         orderby bc.Name
                         select bc;
            ViewBag.TopicId = new SelectList(topics, "Id", "Name", null);

            _logger.LogInformation($"   -   StepOne {DateTime.UtcNow.ToLongTimeString()}");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> StepTwo(MessageDto mvm)
        {
            if (ModelState.IsValid)
            {
                var topics = from bc in _context.Topics
                             orderby bc.Name
                             select bc;
                ViewBag.TopicId = new SelectList(topics, "Id", "Name", null);

                _logger.LogInformation($"   -   StepTwo {DateTime.UtcNow.ToLongTimeString()}");
                return View(mvm);
            }
            return View("StepOne");
        }

        [HttpPost]
        public async Task<IActionResult> SendForm(MessageDto m)
        {
            if (ModelState.IsValid)
            {
                EmailSender emailSenderFromConfig = new EmailSender(_emailConfigurationSettings);
                bool sendEmailResult = false;
                sendEmailResult = await emailSenderFromConfig.SendEmailAsync(m.EmailTo, "temat", m.MessageText, false);
                if (sendEmailResult)
                {
                    _logger.LogInformation($"   -   SendMessageAsync success");
                }
                else
                {
                    _logger.LogInformation($"   -   SendMessageAsync failed");
                }

                var info = new Info();


                int createdId = _wizardService.Add(m);
                if (sendEmailResult && createdId > 0)
                {
                    info.Id = createdId;
                    info.Information = "Wysłano wiadomość i zarejestrowano pod numerem ";
                }
                else
                {
                    info.Information = "Nie udało się utworzyć i wysłać wiadomości";
                }
                return View("Result", info);
                //return RedirectToAction("Messages");
            }
            return View("StepTwo");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WizardForm/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WizardForm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Wizard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Wizard" asp-action="StepOne">Wizard</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Wizard" asp-action="Messages">Messages</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Wizard" asp-action="Index">Index</a>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Api - <a asp-area="" asp-controller="Home" asp-action="StepOne">Form</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WizardForm/Views/Wizard/Index.cshtml
@model Dictionary<string, StepViewModel>

@{
    var p1 = Model["S1"].Position;
    var p2 = Model["S2"].Position;
}

<p>@p1  @p2</p>

@* @foreach (var item in Model.Keys.ToArray())
{
    await Html.RenderPartialAsync(item);
} *@

@foreach (var item in Model.Values.ToArray())
{
    <p>@item.Position</p>
}

@{
    await Html.RenderPartialAsync("S1");
}

WizardForm/Views/Wizard/Messages.cshtml
@model IEnumerable<Infrastructure.Dto.MessageDto>

@{
    ViewData["Title"] = "Wysłane wiadomości";
}

<h2>Wysłane wiadomości</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailCc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailTo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SendDateTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmailCc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmailTo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SendDateTime)
                </td>
            </tr>
        }
    </tbody>
</table>

WizardForm/Views/Wizard/Result.cshtml
@model WizardForm.Models.Info

<h1>@Model.Information @Model.Id</h1>

WizardForm/Views/Wizard/S1.cshtml
@model Dictionary<string, StepViewModel>

@{
    var s1 = Model["S1"];
    var position = Model["S1"].Position;   
}

<p>S1 @position</p>
<form>
  @* <input asp-for="m1.FirstName" class="form-control"/> *@
</form>

WizardForm/Views/Wizard/S2.cshtml
@model Dictionary<string, StepViewModel>

<p>S2 </p>

WizardForm/Views/Wizard/StepOne.cshtml
@model Infrastructure.Dto.MessageDto
@{
    ViewData["Title"] = "Wizard";
}

<div class="container">
    <form action="/Wizard/StepTwo/" method="POST">
        <div class="col-md-12">
            <div class="row">
                <div class="col-sm-6 form-group">
                    <input asp-for="FirstName" class="form-control" placeholder=@Html.DisplayNameFor(m =>
                        m.FirstName) />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="col-sm-6 form-group">
                    <input asp-for="LastName" class="form-control" placeholder=@Html.DisplayNameFor(m => m.LastName) />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="col-sm-6 form-group">
                    <input asp-for="EmailTo" class="form-control" placeholder=@Html.DisplayNameFor(m => m.EmailTo) />
                    <span asp-validation-for="EmailTo" class="text-danger"></span>
                </div>

            </div>
            <div class="row">
                <div class="col-sm-12 form-group">
                    <input type="submit" value="NEXT >">
                </div>
            </div>
        </div>
    </form>
</div>

WizardForm/Views/Wizard/StepTwo.cshtml
@model Infrastructure.Dto.MessageDto
@{
    ViewData["Title"] = "Wizard";
}

<div class="container">
    <form action="/Wizard/SendForm/" method="POST">
        @* data-ajax-method="POST"
            data-ajax-update="#returnMessage"
            data-ajax-mode="replace"
            data-ajax-loading="#loading-gif"
            data-ajax-success="OnSuccessMessage"
            data-ajax-failure="OnFailureMessage"
            data-ajax="true"> *@

        <input asp-for="FirstName" type="hidden" />
        <input asp-for="LastName" type="hidden" />
        <input asp-for="EmailTo" type="hidden" />

        <div class="col-md-12">
            <div class="row">
                <div class="col-sm-6">
                    <label asp-for="TopicId" class="control-label"></label>
                    <select asp-for="TopicId" class="form-control" asp-items="ViewBag.TopicId">
                        <option value="">-- Select topic category --</option>
                    </select>
                    <span asp-validation-for="TopicId" class="text-danger" />
                </div>
                <div class="col-sm-6">
                    <textarea asp-for="MessageText" rows="5" class="form-control" placeholder=@Html.DisplayNameFor(m =>
                        m.MessageText)></textarea>
                    @* <span asp-validation-for="MessageText" class="text-danger"></span> *@
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 form-group">
                    <input type="submit" value="SEND">
                </div>
            </div>
        </div>
    </form>
</div>